version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: express_auth_db
    restart: always
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - express_auth_db_data:/var/lib/mysql

volumes:
  express_auth_db_data:
    driver: local